### ISSUE TITLE
Create a Landing Page for html 

### ISSUE THREAD

**Issue by GDSCIIITSurat** [GDSCIIITSurat/Bill-Splitter#14]
Create a responsive landing Page for html branch, the Page that appears when we visit the website.

**Comment by SarwinR** [comment]
Are there any references of how the page should look like?

**Comment by GDSCIIITSurat** [comment]
It should have the name of the project, on the main page, a suitable background of your choice, and a small description about the project.

**Comment by SarwinR** [comment]
ok, I can do it.

**Comment by GDSCIIITSurat** [comment]
Okay you can start working on this issue then

**Comment by akki2104** [comment]
I want to work on this issue

**Comment by GDSCIIITSurat** [comment]
@SarwinR what is the status of this issue?

**Comment by SarwinR** [comment]
Almost done

**Comment by SarwinR** [comment]
![image](https://user-images.githubusercontent.com/64829298/194148972-29e4b557-d906-4bcd-a388-10ecdbfb7a17.png)

@GDSCIIITSurat  Is there anything else that I should add?

**Comment by GDSCIIITSurat** [comment]
No its fine
