### ISSUE TITLE
Add signup feature (backend)

### ISSUE THREAD

**Issue by Averek7** [GDSCIIITSurat/Bill-Splitter#16]
implement signup feature to the bill-splitter backend

**Comment by GDSCIIITSurat** [comment]
You can work on this issue

**Comment by mandyval17** [comment]
sir my backend is ready both login and sign up so if you can assign me this issue i can resolve within few hours

**Comment by GDSCIIITSurat** [comment]
Just talk with avanish singh, he is working on this issue. If he allows you can work instead of him

**Comment by GDSCIIITSurat** [comment]
@mandyval17 you can work on this issue
