### ISSUE TITLE
Create Signup page for frontend (react branch)

### ISSUE THREAD

**Issue by GDSCIIITSurat** [GDSCIIITSurat/Bill-Splitter#18]
Create a responsive sign-up page(frontend) for the react version of this webapp

**Comment by Nach-33** [comment]
What input fields are required for signing up?

**Comment by GDSCIIITSurat** [comment]
Email, name, password, confirm password, contact number.

**Comment by Worriedhenry** [comment]
I want to work on this issue .

**Comment by Nach-33** [comment]
I also want to work on this issue

**Comment by GDSCIIITSurat** [comment]
Only one of you can work on this issue, i am assigning this issue to @Worriedhenry.

@Nach-33 you can make the landing page for react version. Just create a new issue regarding this and tag me

**Comment by Nach-33** [comment]
Sir I had started to work on it and I'm ready with the sign up page. Can you assign this to me instead?

**Comment by GDSCIIITSurat** [comment]
@Worriedhenry what is your progress, if you are fine can we assign this task to @Nach-33

**Comment by Worriedhenry** [comment]
> @Worriedhenry what is your progress, if you are fine can we assign this task to @Nach-33

Sir i am almost done with it .
