### ISSUE TITLE
Page not rendering on reload on netlify

### ISSUE THREAD

**Issue by vivek2293** [GDSCIIITSurat/Bill-Splitter#28]
Issue: If we move to any other webpage (except root) and reload it. It will give the error- Page Not Found.
![image](https://user-images.githubusercontent.com/95707356/194162926-c301fb36-6606-40e3-89ab-c0cfd2ad3c06.png)

**I want to work on this issue.**

**Comment by GDSCIIITSurat** [comment]
Okay you can work on this
