### ISSUE TITLE
Create Login Page frontend in React JS  

### ISSUE THREAD

**Issue by GDSCIIITSurat** [GDSCIIITSurat/Bill-Splitter#3]
You have to create a login page(frontend only) in the react branch (react-bill-splitter) which will have email, and password.
Make sure you make pull request to the react-bill-splitter branch.
The login page should be responsive.

Whoever is interested can comment under this issue, you will be assigned this task.

**Comment by jitanshuraut** [comment]
I want to take this task

**Comment by Worriedhenry** [comment]
@GDSCIIITSurat I want to work on this issue, i have a pretty good exprerience with this.

**Comment by GDSCIIITSurat** [comment]
> I want to take this task

Okay @jitanshuraut you can work on this issue

**Comment by GDSCIIITSurat** [comment]
> @GDSCIIITSurat I want to work on this issue, i have a pretty good exprerience with this.

This issue has been assigned to someone else, you can create a new issue on some other bug or feature.

You can work on the signup page issue.
