### ISSUE TITLE
 landing page of React js

### ISSUE THREAD

**Issue by jitanshuraut** [GDSCIIITSurat/Bill-Splitter#34]
sample UI -->https://www.figma.com/file/1C0IRbyxxEGFj5IeYknaHo/Untitled?node-id=0%3A1     
<img width="585" alt="image" src="https://user-images.githubusercontent.com/96559286/194322474-4677dd7d-91e6-4aab-bf8c-5cad9ba68879.png">

**Comment by GDSCIIITSurat** [comment]
This page will come after login, this is fine but this is not landing page.
For landing page, it should have the name of the app, short description and option for login/signup

**Comment by jitanshuraut** [comment]
so can I start with this or wait for the landing page?

**Comment by jitanshuraut** [comment]
or first create a landing page

**Comment by GDSCIIITSurat** [comment]
you can take reference of any big application, they have their app name, some description, and a background image.

![image](https://user-images.githubusercontent.com/93446269/194329255-67d218aa-6842-47e7-b335-0641bf64a6a5.png)

You can ignore the navbar, not required for now

**Comment by GDSCIIITSurat** [comment]
> 

yeah first create landing page

**Comment by GDSCIIITSurat** [comment]
so should i assign you this issue @jitanshuraut

**Comment by jitanshuraut** [comment]
yes
