### ISSUE TITLE
FAQ page (HTML Branch)

### ISSUE THREAD

**Issue by shreyshah-06** [GDSCIIITSurat/Bill-Splitter#37]

**Comment by GDSCIIITSurat** [comment]
Please provide description also about what things you will make in this

**Comment by shreyshah-06** [comment]
Will be adding the frequently asked questions which users usually have doubt in. It will help users to clear their doubts in an easy way which includes explanation of some features and other things to users and enhance the user experience.

**Comment by GDSCIIITSurat** [comment]
Okay you can work on this
