### ISSUE TITLE
improvement in ui of login and signup page(HTML Branch)

### ISSUE THREAD

**Issue by akki2104** [GDSCIIITSurat/Bill-Splitter#41]
the login page and sign up page needs improvement in color palette and design

**Comment by GDSCIIITSurat** [comment]
Login signup is fine for now, if you want you can make a better landing page in html branch.

**Comment by akki2104** [comment]
Ok I am starting to work on that.

**Comment by GDSCIIITSurat** [comment]
Make a new issue regarding that and close this one
