### ISSUE TITLE
Password visible in signup page

### ISSUE THREAD

**Issue by rutwik2514** [GDSCIIITSurat/Bill-Splitter#44]
after entering the password, Password is visible in signup page, whereas it should be in dot format.I would like to work on this issue.

**Comment by rutwik2514** [comment]
In react frontend

**Comment by rutwik2514** [comment]
as well as in email field, it is acceptable if it's not email, in contact number, letters are acceptable. Need to change that too

**Comment by GDSCIIITSurat** [comment]
Okay you can work on this
