### ISSUE TITLE
maybe the text is getting bigger in  Deploy Preview (is it?)

### ISSUE THREAD

**Issue by jitanshuraut** [GDSCIIITSurat/Bill-Splitter#46]
Deploy Preview:----->
<br>
![image](https://user-images.githubusercontent.com/96559286/194582601-ae078a4f-a702-4774-b7de-e1ef9575d3b6.png)
<br>original:------------->
<br>
![image](https://user-images.githubusercontent.com/96559286/194582694-a6951acc-3081-45f6-8f0a-82f5802c67f5.png)

**Comment by GDSCIIITSurat** [comment]
Not needed for now
