### ISSUE TITLE
Improving Sign page (HTML Branch)

### ISSUE THREAD

**Issue by Worriedhenry** [GDSCIIITSurat/Bill-Splitter#47]
Adding more input fields to signup and improving UI . Also Making Password visible as user is typing it first time keeping retype hidden.While entering data in capital letters the Initial letter is to close to border(need some padding ) . On Registering the page reload , which is not expected .And some other issues

**Comment by GDSCIIITSurat** [comment]
Dont add any more fields, you can work on other things written
