### ISSUE TITLE
Sending Data to the backend via axios in React Signup

### ISSUE THREAD

**Issue by vivek2293** [GDSCIIITSurat/Bill-Splitter#48]
I can validate the data sent to the backend via Axios. I can also validate if the backend is working properly for the requests. I had done this before in the projects too, therefore I want to work on this issue.

**Comment by GDSCIIITSurat** [comment]
There are some problems right now in backend, after they are resolved you can continue to work on backend

**Comment by vivek2293** [comment]
Can I know the issues? Maybe I can help to solve them.
