### ISSUE TITLE
Password reset with captcha verification Page(HTML)

### ISSUE THREAD

**Issue by Worriedhenry** [GDSCIIITSurat/Bill-Splitter#58]
Using  random captcha to reset Password in case user forgets it.

**Comment by GDSCIIITSurat** [comment]
Cam you share any website which uses this, or elaborate how does this work

**Comment by Worriedhenry** [comment]
It's mostly frontend thing ,as we don't have any data to use any other method  for authentication like OTP or something . If i am missing something please let me know .
It's work something like this : -
A random captcha is genrated on screen and if user fills it correctly then it show success else failure . Mostly UI work .
Once Backend is deployed and user data is there , i will update it with real like password reset page

**Comment by GDSCIIITSurat** [comment]
So captcha will he shown after otp and new password is set right?

**Comment by Worriedhenry** [comment]
No to send OTP i need mail id but as we are not storing data anywhere so there no way to verify mail id . So if mail id is not verified then OTP cannot be sent to any random Email. Currently i will just make frontend page for it and for it's functionality i will later create another issue when backend is ready to use . That's my plan so far.
