### ISSUE TITLE
Reset password backend

### ISSUE THREAD

**Issue by Prasang023** [GDSCIIITSurat/Bill-Splitter#59]
What i will create:
- Use jwt to create an auto expiration token.
- Pass the token in a link as parameter and mail the link to the required email.
- On clicking the link, user is redirected to a page where new password and confirm password can be entered.
- Frontend needs to check the validity of access token to check whether timeout has happened or not.

**Comment by GDSCIIITSurat** [comment]
okay you can work on this issue
