### ISSUE TITLE
Password suggestion to user and captcha verification  (REACT)

### ISSUE THREAD

**Issue by Worriedhenry** [GDSCIIITSurat/Bill-Splitter#87]
This update will suggest user a strong password on Signup and also add captcha verification to signup to prevent bot.

**Comment by GDSCIIITSurat** [comment]
suggest a password, or check if the password is strong enough?

**Comment by Worriedhenry** [comment]
I will add both cheak and suggest.

**Comment by GDSCIIITSurat** [comment]
https://superuser.com/questions/1508442/how-to-ask-firefox-to-suggest-a-password-when-filling-out-registration-form-on-t

You can refer this article, do something like this for suggesting password, it should not give a list of options to select a password, but something like generating a password and filling in the password box.

**Comment by Worriedhenry** [comment]
Ok the password field will be already filled with a strong random password when user opens the signup page , it can be changed if user wants . Is that good?

**Comment by GDSCIIITSurat** [comment]
It is better if initially it will be empty and there should be a button called generate password, after the button is client,then the password will be filled.

**Comment by Worriedhenry** [comment]
Ok
